social/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

social/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),
]

social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<slug:username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<slug:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

social/groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

social/posts/models.py
from django.db import models
from django.urls import reverse
import misaka
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

social/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

social/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember
from django.shortcuts import get_object_or_404
from django.contrib import messages
from . import models

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning already a member')
        else:
            messages.success(self.request,('You are now a member!'))

        return super().get(self.request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self,*args,**kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')
        return super().get(self.request,*args,**kwargs)

social/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib import messages

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ['user','group']

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object  = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related =('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

social/social/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

social/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
  <div class="container">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-default" type="submit" value="Login">
    </form>
  </div>
{% endblock %}

social/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
  <div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-default" type="submit" value="Sign Up">
    </form>
  </div>
{% endblock %}

social/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      {% block pregroup %}{% endblock %}
      {% block group_content %}{% endblock %}
      {% block postgroup %}{% endblock %}
    </div>
  </div>
{% endblock content %}

social/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
  <h1>{{ group.name }}</h1>
  <h2>Member Count: {{ group.members.count }}</h2>
  <div class="content">
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
    {% else %}
      <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
    {% endif %}
  </div>
{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    {% if group.posts.count == 0 %}
      <h2>No posts in this group yet!</h2>
    {% else %}
      {% for post in group.posts.all %}
        {% include "posts/_post.html" %}
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

social/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}
{% block group_content %}
  <h4>Create a new goup!</h4>
  <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
  </form>
{% endblock %}

social/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2>Welcome back!
          <a href="{% url 'posts:for_user' username=user.username %}">
            @{{ user.username }}
          </a>
        </h2>
      {% endif %}
      <h2>Groups</h2>
      <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
      <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign">Create New Group!</span>
      </a>
    {% endif %}
  </div>
{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %}
        <a href="{% url 'groups:single' slug=group.slug %}">
          <h3 class="title list-group-item-heading">{{ group.name }}</h3>
          <div class="list-group-item-text container-fluid">
            {{ group.description_html|safe }}
            <div class="row">
              <div class="col-md-4">
                <span class="badge">{{ group.members.count }}</span>
                member{{ group.members.count|pluralize }}
              </div>
              <div class="col-md-4">
                <span class="badge">{{ group.posts.count }}</span>
                post{{ group.posts.count|pluralize }}
              </div>
            </div>
          </div>
        </a>
        <br><br>
      {% endfor %}
    </div>
  </div>
{% endblock %}

social/posts/templates/posts/_post.html
<div class="post media">
  <h3>{{ post.message_html|safe }}</h3>
  <div class="media-body">
    <!-- <strong>{{ post.user.username }}</strong> -->
    <h5 class="media-heading">
    <span class="username">
      <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
    </span>
    <time class="time">
      <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>
    </time>
    </h5>
    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
          <span class="glyphicon glyphicon-remove text-danger" aria-hidden='true'></span>
          <span class="text-danger icon-label">Delete</span>
        </a>
      {% endif %}
    </div>
  </div>
</div>

social/posts/templates/posts/post_base.html
{% extends "base.html" %}
{% block content %}
  <div class="posts-page">
    <div class="container">
      <div class="row">
        {% block prepost %}{% endblock %}
        {% block post_content %}{% endblock %}
        {% block post_post %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

social/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_post %}
  <h3>Are you sure you want to delete this post?</h3>
  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>
  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a class="btn btn-simple btn-large btn-default" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancle</a>
  </form>
{% endblock %}

social/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_post %}
  <div class="post_content">
    {% include "posts/_post.html" %}
  </div>
{% endblock %}

social/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
  <h4>Create a new post</h4>
  <form id="postForm" action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class="btn btn-primary btn-large">
  </form>
{% endblock %}

social/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title">Your Groups</h5>
          <ul class="list-unstyled">
            {% for member_group in get_user_groups %}
              <li class="group li-with-bullet">
                <a href="{% url 'groups:single' slug=member_group.group.slug %}"></a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endif %}
    <div class="card card-with-shadow">
      <div class="content">
        <h5 class="title">All Groups</h5>
        <ul class="list-unstyled">
          {% for other_group in get_other_groups %}
            <li class="group li-with-bullet">
              <a href="{% url 'groups:single slug=other_group.slug' %}"></a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}


{% block post_post %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}

social/posts/templates/posts/user_post_lsit.html
{% extends "posts/post_base.html" %}
{% block prepost %}
  <div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
  </div>
{% endblock %}

{% block post_post %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}

social/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "/social/css/master.css" %}">
      <script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>
  </head>
  <body>

    <nav class="navbar mynav" role="navigation" id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}">Post</a></li>
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'groups:create' %}">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>
  </body>
  <script type="text/javascript" src="{% static "social/js/master.js" %}">

  </script>
</html>

social/templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1>Welcome to Star Social!</h1>
{% endblock %}

social/templates/test.html
{% extends "base.html" %}
{% block content %}
  <h1>You are now logged in!</h1>
{% endblock %}

social/templates/thanks.html
{% extends "base.html" %}
{% block content %}
  <h1>Thanks for visiting, come back soon!</h1>
{% endblock %}