prototype/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post-list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post-detail'),
    path('post/create/',views.PostCreateView.as_view(),name='create_post'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='remove_post'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft'),
    path('post/<int:pk>/publish/', views.post_publishing, name='post_publishing'),
    path('post/<int:pk>/comments', views.CommentCreateView.as_view(),name='add_comment_to_post'),
    path('comment/<int:pk>/remove', views.CommentDeleteView.as_view(), name='remove_comment'),
    path('comment/<int:pk>/approve',views.approve_comment_view,name='approve_comment'),
]

prototype/prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('shop/',include('shop.urls')),
    path('blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prototype/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    text_preview = models.TextField(max_length=400)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="blog/", blank=True)
    creating_date = models.DateTimeField(default=timezone.now)
    publishing_date = models.DateTimeField(null=True,blank=True)

    def publish(self):
        self.publishing_date = timezone.now()
        self.save()

    def approved_comments_set(self):
        return self.comments.filter(is_approved=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    class Meta:
        ordering = ('is_approved','-creating_date')

    author = models.CharField(max_length=30)
    text = models.TextField(max_length=200)
    email = models.EmailField()
    # Verify_exists???
    website = models.URLField(blank=True)
    post = models.ForeignKey('Post', related_name='comments' ,on_delete=models.CASCADE)
    creating_date = models.DateTimeField(default=timezone.now)
    is_approved = models.BooleanField(default=False)

    def approve(self):
        self.is_approved = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

prototype/blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'email','website', 'text')

        # widgets = {
        #     'author': forms.TextInput(attrs={'class':'col-sm-4 blank-arrow'}),
        #     'email': forms.TextInput(attrs={'class':'col-sm-4 blank-arrow'}),
        #     'website': forms.TextInput(attrs={'class':'col-sm-4 blank-arrow'}),
        # }

prototype/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post,Comment
from shop import models
from blog.forms import PostForm, CommentForm
from django.utils import timezone
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView,DeleteView)


# class HomeView(TemplateView):
#     template_name = 'home.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(publishing_date__lte=timezone.now()).order_by('-publishing_date')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['main_categories'] = models.Category.objects.filter(is_main=True)
        return context

class PostDetailView(DetailView):
    model = Post

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['main_categories'] = models.Category.objects.filter(is_main=True)
        context['comment_form'] = CommentForm()
        return context

    def post(self, *args, **kwargs):
        form = CommentForm(self.request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            post = get_object_or_404(Post,id=self.kwargs['pk'])
            comment.post = post
            form.save(commit=True)
        else:
            print("*** INVALID FORM ***")
        return redirect('blog:post-detail', pk=self.kwargs['pk'])

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    form_class = PostForm

class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(publishing_date__isnull=True,creating_date__lte=timezone.now()).order_by('-creating_date')

class CommentCreateView(CreateView):
    model = Comment
    template_name = 'blog/post_detail.html'
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post = get_object_or_404(Post,id=self.kwargs['pk'])
        comment.post = post
        return super(CommentCreateView, self).form_valid(form)

class CommentDeleteView(LoginRequiredMixin,DeleteView):
    model = Comment
    template_name = 'blog/comment_delete.html'

    def get_success_url(self):
        comment = get_object_or_404(Comment,pk=self.kwargs['pk'])
        print(comment.post.id)
        return reverse_lazy('blog:post_detail',kwargs={'pk':comment.post.id})

@login_required
def post_publishing(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)

@login_required
def approve_comment_view(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk=comment.post.pk)

prototype/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Acme|Indie+Flower&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <div class="container">
      {% block import %}
      {% endblock %}
    </div>
  </body>
</html>

prototype/blog/templates/blog/comment_delete.html
{% extends "base.html" %}
{% block import %}
  <div class="jumbotron">
      <form method="POST">
          {% csrf_token %}
          <h2>Are you sure you want to delete {{ comment.text }}?</h2>
          <input class="btn btn-success" type="submit" value="Confirm">
          <a class="btn btn-warning" href="{% url 'blog:post_detail' pk=comment.post.pk %}">Cancle</a>
      </form>
  </div>
{% endblock %}

prototype/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block import %}
  <div class="jumbotron">
    <form class="form-group" method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <button class="btn btn-success" type="submit">Send</button>
    </form>
  </div>
{% endblock %}

prototype/blog/templates/blog/post_delete.html
{% extends "base.html" %}
{% block import %}
  <div class="jumbotron">
      <form method="POST">
          {% csrf_token %}
          <h2>Are you sure you want to delete {{ post.title }}?</h2>
          <input class="btn btn-success" type="submit" value="Confirm">
          <a class="btn btn-warning" href="{% url 'blog:post_detail' pk=post.pk %}">Cancle</a>
      </form>
  </div>
{% endblock %}

prototype/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block import %}
  <div class="jumbotron">
    <div class="post-detail">
      <h2 class="title">{{ post.title }}</h2>
      <h4 class="text">{{ post.text }}</h4>
      <h5>Created on: {{post.creating_date}}</h5>
      {% if post.publishing_date %}
        <h5>Published on: {{ post.publishing_date }}</h5>
      {% else %}
        <a class="btn btn-primary" href="{% url 'blog:post_publishing' pk=post.pk%}">Publish</a>
      {% endif %}
      <a class="btn btn-danger" href="{% url 'blog:remove_post' pk=post.pk %}">Delete</a>
      <a class="btn btn-info" href="{% url 'blog:edit_post' pk=post.pk %}">Edit</a>
    </div>
  <br>
  <h3 style="text-align:center;margin-bottom:5%"><b>Comments</b> <a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add</a></h3>
  {% for comment in post.comments.all %}
    <p><b>{{ comment.author }}</b>: {{ comment.text }}</p>
    {% if not comment.is_approved %}
      <a class="btn btn-success" href="{% url 'blog:approve_comment' pk=comment.pk %}">Approve</a>
    {% else %}
      <p>Posted on: {{ comment.creating_date }}</p>
    {% endif %}
    <a class="btn btn-danger" href="{% url 'blog:remove_comment' pk=comment.pk %}">Remove</a>
    <hr>
  {% empty %}
    <p>No comments yet!</p>
  {% endfor %}
  </div>
{% endblock %}

prototype/blog/templates/blog/post_draft_list.html
{% extends "base.html" %}
{% block import %}
  <div class="jumbotron">
    <h1>Drafts list</h1>
    {% for post in post_list %}
    <a href="{% url 'blog:post_detail' pk=post.pk %}">
      <div class="post-list">
        <h2>{{ post.title }}</h2>
        <h4>Created on: {{ post.creating_date }}</h4>
        {% for comment in post.comments.all %}
          {% if comment.is_approved %}
            <p><b>{{ comment.author }}</b>: {{ comment.text }}</p>
          {% endif %}
        {% endfor %}
      </div>
    </a>
    {% empty %}
    {% endfor %}
  </div>
{% endblock %}

prototype/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block import %}
  <div class="jumbotron">
    <form class="form-group" method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <button class="btn btn-success" type="submit">Send</button>
    </form>
  </div>
{% endblock %}

prototype/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% block import %}
<div class="jumbotron">
  {% for posts in post_list %}
  <a href="{% url 'blog:post_detail' pk=posts.pk %}">
    <div class="post-list">
        <p class="title"><b>{{ posts.title }}</b></p>
        <p class="text">{{ posts.text }}</p>
        <p><b>Comments:</b> {{posts.approved_comments_set.count}}</p>
        <p class="username">@{{ posts.author }}</p>
    </div>
  </a>
  {% empty %}
    <li>Nothing Found!</li>
  {% endfor %}
</div>
{% endblock %}