prototype/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post-list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post-detail'),
    path('post/create/',views.PostCreateView.as_view(),name='create_post'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='remove_post'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft'),
    path('post/<int:pk>/publish/', views.post_publishing, name='post_publishing'),
    path('post/<int:pk>/comments', views.CommentCreateView.as_view(),name='add_comment_to_post'),
    path('comment/<int:pk>/remove', views.CommentDeleteView.as_view(), name='remove_comment'),
    path('comment/<int:pk>/approve',views.approve_comment_view,name='approve_comment'),
]

prototype/prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('shop/',include('shop.urls')),
    path('blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prototype/shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('products/', views.ProductList.as_view(),name='products-view'),
    path('products/add/',views.CreateProduct.as_view(),name='products-add'),
    path('products/<slug:slug>/', views.ProductDetail.as_view(),name='products-detail'),
    path('products/<slug:slug>/add_to_cart/',views.add_to_cart,name='add-to-cart-view'),
    path('products/<slug:slug>/decrease_from_cart/',views.decrease_from_cart,name='decrease-from-cart-view'),
    path('products/<slug:slug>/remove_from_cart/',views.remove_from_cart,name='remove-from-cart-view'),
    path('products/delete/<slug:slug>/',views.DeleteProduct.as_view(),name='products-delete'),
    path('category/<slug:slug>',views.CategoryView.as_view(),name='category-view'),
    path('carts/', views.CartList.as_view(),name='carts-view'),
    path('carts/<int:pk>/',views.CartDetail.as_view(),name='carts-detail'),
    path('orders/', views.OrderList.as_view(),name='orders-view'),
    path('orders/<int:pk>/',views.OrderDetail.as_view(),name='orders-detail'),
    path('publish/',views.PublishList.as_view(),name='publish-view'),
    path('publish/<slug:slug>/',views.PublishView.as_view(),name='publishing'),
    path('payment/<int:pk>/',views.PaymentView,name='payment-view'),
    path('wishlist/<slug:slug>',views.WishListView.as_view(),name='wishlist-view'),
    path('wishlist/add/<slug:slug>/',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/remove/<slug:slug>/',views.remove_from_wishlist,name='remove-from-wishlist'),
    path('checkout/',views.CheckoutTemplateView.as_view(),name='checkout-view'),
]

prototype/shop/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone

User = get_user_model()

class Category(models.Model):
    name =  models.CharField(max_length=25)
    sub_category = models.ManyToManyField('self',blank=True)
    is_main = models.BooleanField(default=False)
    slug = models.SlugField(allow_unicode=True,unique=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=70)
    category = models.ForeignKey(Category, related_name='product_category', on_delete=models.SET_NULL, null=True)
    detail = models.CharField(max_length=150)
    slug = models.SlugField(allow_unicode=True,unique=True,blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to="product/")
    is_published = models.BooleanField(default=False)
    publish_time = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.is_published = True
        self.publish_time = timezone.now()
        self.save()

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('shop:products-detail',kwargs={'slug':self.slug})

    def __str__(self):
        return f'{self.name}'

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='cart_products', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def total_cart(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'

class Order(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    orderitems = models.ManyToManyField(Cart,related_name='order_items')
    created_at = models.DateTimeField(auto_now_add=True)

    def total_order(self):
        total = 0
        for order_item in self.orderitems.all():
            total += order_item.total_cart()
        return total

    def __str__(self):
        return f'{self.user.username} order {self.pk}'

class SuccessfulPayment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    orderitems = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user}'


class ProductFilter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    price1 = models.IntegerField(blank=True, null=True)
    price2 = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.price1}-{self.price2}'

class Wishlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    list = models.ManyToManyField(Product)
    slug = models.SlugField(allow_unicode=True,unique=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.user.username)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.user}'

class ProductComment(models.Model):
    class Meta:
        ordering = ('is_approved','-creating_date')

    author = models.CharField(max_length=30)
    text = models.TextField(max_length=200)
    email = models.EmailField()
    # Verify_exists???
    website = models.URLField(blank=True)
    product = models.ForeignKey(Product, related_name='product_comments' ,on_delete=models.CASCADE)
    creating_date = models.DateTimeField(default=timezone.now)
    is_approved = models.BooleanField(default=False)

    def approve(self):
        self.is_approved = True
        self.save()

    def get_absolute_url(self):
        return reverse('shop:products-view')

    def __str__(self):
        return self.text

prototype/shop/forms.py
from django import forms
from .models import ProductFilter, ProductComment

class PriceFilterForm(forms.ModelForm):
    class Meta:
        model = ProductFilter
        fields = ('price1','price2')

class ProductCommentForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ('author', 'email', 'website', 'text')

prototype/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, Http404
from . import models
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import PriceFilterForm, ProductCommentForm


User = get_user_model()

class ProductList(generic.ListView):
    model = models.Product
    template_name = 'shop/shop.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        try:
            a = get_object_or_404(models.ProductFilter,user=self.request.user)
            qs = queryset.filter(price__range=(a.price1,a.price2))
            a.delete()
            return qs.filter(is_published=True).order_by('-publish_time')
        except:
            pass
        return queryset.filter(is_published=True).order_by('-publish_time')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        from django.db.models import Q
        print("\n\n\n")
        print("Puma")
        print(models.Product.objects.filter(category__name__iexact="Puma"))
        print("\nNot Published")
        print(models.Product.objects.filter(is_published=True))
        print("\n Puma.published")
        print(models.Product.objects.filter(category__name__iexact="Puma").filter(is_published=True))
        print("\n Puma , Published")
        print(models.Product.objects.filter(Q(category__name__iexact="Puma")|Q(is_published=True)))
        print("\n\n\n")
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        context['price_filter_form'] = PriceFilterForm()
        return context

    def post(self, *args, **kwargs):
        print("\n\n\n\nPOST REQUEST FOUND\n\n\n\n")
        if 'price1' in self.request.POST:
            form = PriceFilterForm(self.request.POST)
            if form.is_valid():
                self.object  = form.save(commit=False)
                self.object.user = self.request.user
                form.save(commit=True)
            else:
                print("*** INVALID FORM ***")
        return redirect('shop:products-view')



class ProductDetail(LoginRequiredMixin,generic.DetailView):
    model = models.Product
    template_name = 'shop/product-details.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['product_comment_form'] = ProductCommentForm()
        try:
            product = get_object_or_404(models.Product,slug=self.kwargs.get('slug'),is_published=True)
            d = models.Cart.objects.filter(user=self.request.user,product=product)
            context['quantity_by_product'] = d[0].quantity
        except:
            pass
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        try:
            this_product = get_object_or_404(models.Product,slug=self.kwargs.get('slug'),is_published=True)
            pdc = models.Product.objects.filter(category__sub_category__name__exact=this_product.category.sub_category.all()[0].name).order_by('-publish_time')
            context['related_products'] = pdc[:4]
        except:
            pass
        return context

    def post(self, *args, **kwargs):
        form = ProductCommentForm(self.request.POST)
        print("\n\n\n\npost request\n\n\n\n")
        if form.is_valid():
            productcomment = form.save(commit=False)
            product = get_object_or_404(models.Product,slug=self.kwargs['slug'])
            productcomment.product = product
            form.save(commit=True)
        else:
            print("*** INVALID FORM ***")
        return redirect('shop:products-detail', slug=self.kwargs['slug'])


class CreateProduct(LoginRequiredMixin,generic.CreateView):
    model = models.Product
    fields = ('name','category','detail','price','image')

    # def form_valid(self,form):
    #     self.object  = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.save()
    #     return super().form_valid(form)

class DeleteProduct(LoginRequiredMixin,generic.DeleteView):
    model = models.Product
    success_url = reverse_lazy('shop:products-view')

    def delete(self,*args,**kwargs):
        print('Product Deleted')
        return super().delete(*args,**kwargs)

class CategoryView(generic.DetailView):
    model = models.Category
    template_name = 'shop/category.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        return context

class WishListView(generic.DetailView):
    model = models.Wishlist
    template_name = 'shop/wishlist.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        return context

class CartList(LoginRequiredMixin,generic.ListView):
    model = models.Cart

class CartDetail(LoginRequiredMixin,generic.DetailView):
    model = models.Cart

class OrderList(LoginRequiredMixin,generic.ListView):
    model = models.Order

class OrderDetail(LoginRequiredMixin,generic.DetailView):
    model = models.Order
    template_name = 'shop/cart.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.request.user)

class PublishList(LoginRequiredMixin,generic.ListView):
    model = models.Product
    template_name = 'shop/publish.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=False)

class PublishView(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('shop:publish-view')

    def get(self,*args,**kwargs):
        product = get_object_or_404(models.Product,slug=self.kwargs.get('slug'))
        product.publish()
        return super().get(self.request,*args,**kwargs)

class CheckoutTemplateView(generic.TemplateView):
    template_name = 'shop/checkout.html'


@login_required
def PaymentView(request,pk):
    order = get_object_or_404(models.Order,pk=pk)
    sp, spc = models.SuccessfulPayment.objects.get_or_create(user=request.user)
    text = ''
    for i in order.orderitems.all():
        text += str(i)+'\n'
    text += '--------------\n'
    text += sp.orderitems
    sp.orderitems = text
    sp.save()
    models.Cart.objects.filter(user=request.user).delete()
    order.delete()
    return redirect('shop:orders-view')

@login_required
def add_to_cart(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    order_item,created_cart = models.Cart.objects.get_or_create(product=product,user=request.user)
    order_qs,created_order = models.Order.objects.get_or_create(user=request.user)
    # IS THERE AN ORDER?:
    if not created_order:
        # IS THERE A CART WITH THIS PRODUCT
        if order_qs.orderitems.filter(product__slug=product.slug).exists():
            print("add to cart ", order_item, " reuslt quantity = ", order_item.quantity+1)
            order_item.quantity += 1
            order_item.save()
        # THERE IS AN ORDER BUT NO SAME CART
        else:
            order_qs.orderitems.add(order_item)
            print("New item (", order_item ,") added to cart and now add to order ",order_qs)
    # THERE IS NO CART IN ACTIVE ORDER:
    else:
        order_qs.orderitems.add(order_item)
        print("New order (", order_qs ,") created and item (", order_item ,") added to orderitems")
    return redirect('shop:orders-detail',pk=order_qs.pk)

@login_required
def decrease_from_cart(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    order_item = get_object_or_404(models.Cart, product=product,user=request.user)
    order_qs = get_object_or_404(models.Order,user=request.user)

    # IS THERE A CART WITH THIS PRODUCT WITH QUANTITY OF MORE THAN 1
    if not order_qs.orderitems.filter(product__slug=product.slug).filter(quantity__lte=1).exists():
        print("decrease from cart ", order_item, " reuslt quantity = ", order_item.quantity-1)
        order_item.quantity -= 1
        order_item.save()
    # CART WITH THIS PRODUCT WITH QUANTITY OF 1
    else:
        print("Product quantity was one and the cart is deleted")
        order_item.delete()
        # IS THERE JUST ONE CART?:
        if (models.Cart.objects.filter(user=request.user).count() == 0):
            print("***********")
            print("There was only one cart and the order is deleted")
            print("***********")
            order_qs.delete()
            return redirect('shop:orders-view')
    return redirect('shop:orders-detail',pk=order_qs.pk)

@login_required
def remove_from_cart(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    models.Cart.objects.filter(user=request.user,product=product).delete()
    order = get_object_or_404(models.Order,user=request.user)
    # order = models.Order.objects.filter(user=request.user)
    if (models.Cart.objects.filter(user=request.user).count() == 0):
        order.delete()
        return redirect('shop:products-view')
    return redirect('shop:orders-detail', pk=order.pk)

@login_required
def add_to_wishlist(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    wishlist_item,is_created = models.Wishlist.objects.get_or_create(user=request.user)
    wishlist_item.list.add(product)

prototype/shop/templates/shop/cart_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Cart List</title>
  </head>
  <body>
      <p><b>User:</b> {{cart.user}}</p>
      <p><b>Product:</b> {{cart.product}}</p>
      <p><b>Quantity:</b> {{cart.quantity}}</p>
  </body>
</html>

prototype/shop/templates/shop/cart_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Cart List</title>
  </head>
  <body>
    {% for cart in object_list %}
      <a href="{% url 'shop:carts-detail' pk=cart.pk %}"><b>{{cart.user}}: </b>{{cart.product}} with quantity of {{cart.quantity}}</a><br>
    {% endfor %}
  </body>
</html>

prototype/shop/templates/shop/order_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Order {{order.pk}}</title>
    <style>
      a:visited, a{
        color: red;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <p><b>ID:</b> {{order.pk}}</p>
    <p><b>Ordered:</b> {{order.ordered}}</p>
    <p><b>Created:</b> {{order.created_at}}</p>
    {% for item in order.orderitems.all %}
      <p>
        {{item.product.name}}
        {{item.product.price}}
        <a href="{% url 'shop:add-to-cart-view' slug=item.product.slug %}">+</a>
        {{item.quantity}}
        <a href="{% url 'shop:decrease-from-cart-view' slug=item.product.slug %}">-</a>
        {{item.total_cart}}
      </p>
    {% endfor %}
    <p>{{order.total_order}}</p>
    <a href="{% url 'shop:payment-view' pk=order.pk %}">Buy</a>
  </body>
</html>

prototype/shop/templates/shop/order_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Order List</title>
  </head>
  <body>
    {% for order in object_list %}
        <a href="{% url 'shop:orders-detail' pk=order.pk %}"><b>User:</b> {{order.user}}</a>
        <hr>
    {% endfor %}
  </body>
</html>

prototype/shop/templates/shop/product_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Confirm Delete</title>
  </head>
  <body>
    <form method="POST">
      {% csrf_token %}
      <input type="submit" value="Confirm Delete">
      <a href="{% url 'shop:products-view' %}">Cancle</a>
    </form>
  </body>
</html>

prototype/shop/templates/shop/product_detail.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ product.name }}</title>
  </head>
  <body>
    <img src="../../../media/{{ product.image }}" alt="not found">
    <p><b>Name:</b> {{product.name}}</p>
    <p><b>Category:</b> {{product.category}}</p>
    <p><b>Detail:</b> {{product.detail}}</p>
    <p><b>Slug:</b> {{product.slug}}</p>
    <p><b>Price:</b> {{product.price}}</p>
    <p><b>Image:</b> {{product.image}}</p>
    <a href="{% url 'shop:products-delete' slug=product.slug %}" title="delete">Remove</a>
    <a href="{% url 'shop:add-to-cart-view' slug=product.slug %}">Add to cart</a>
    {% for product_item in product.cart_products.all %}
      {% if user == product_item.user %}
        <a href="{% url 'shop:remove-from-cart-view' slug=product.slug %}">Remove from cart</a>
      {% endif %}
    {% endfor %}
  </body>
</html>

prototype/shop/templates/shop/product_form.html
{% load bootstrap3 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Add Product</title>
  </head>
  <body>
    <h4>Create a new product:</h4>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="Publish">
    </form>
  </body>
</html>

prototype/shop/templates/shop/product_list.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Product List</title>
  </head>
  <body>
    {% for product in object_list %}
        <a href="{% url 'shop:products-detail' slug=product.slug %}">
        <img src="../../media/{{ product.image }}" alt="not found"></a>
        <p><b>Name:</b> {{product.name}}</p>
        <hr>
    {% endfor %}
    <a href="{% url 'shop:products-add' %}">+ Add Product +</a>
  </body>
</html>

prototype/shop/templates/shop/publish.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Product List</title>
  </head>
  <body>
    {% for product in object_list %}
        <a href="{% url 'shop:products-detail' slug=product.slug %}">
        <img src="../../media/{{ product.image }}" alt="not found"></a>
        <p><b>Name:</b> {{product.name}}</p>
        <a href="{% url 'shop:publishing' slug=product.slug %}">Publish</a>
        <hr>
    {% endfor %}
    <a href="{% url 'shop:products-add' %}">+ Add Product +</a>
  </body>
</html>